//go:build go1.22

// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BodyAreaKey.
const (
	Body             BodyAreaKey = "body"
	Growth           BodyAreaKey = "growth"
	Heart            BodyAreaKey = "heart"
	Home             BodyAreaKey = "home"
	Journeys         BodyAreaKey = "journeys"
	Mind             BodyAreaKey = "mind"
	Money            BodyAreaKey = "money"
	Papers           BodyAreaKey = "papers"
	Responsibilities BodyAreaKey = "responsibilities"
	Self             BodyAreaKey = "self"
	Work             BodyAreaKey = "work"
)

// Valid indicates whether the value is a known member of the BodyAreaKey enum.
func (e BodyAreaKey) Valid() bool {
	switch e {
	case Body:
		return true
	case Growth:
		return true
	case Heart:
		return true
	case Home:
		return true
	case Journeys:
		return true
	case Mind:
		return true
	case Money:
		return true
	case Papers:
		return true
	case Responsibilities:
		return true
	case Self:
		return true
	case Work:
		return true
	default:
		return false
	}
}

// Defines values for BodyAreaPhase.
const (
	P1 BodyAreaPhase = "P1"
	P2 BodyAreaPhase = "P2"
	P3 BodyAreaPhase = "P3"
)

// Valid indicates whether the value is a known member of the BodyAreaPhase enum.
func (e BodyAreaPhase) Valid() bool {
	switch e {
	case P1:
		return true
	case P2:
		return true
	case P3:
		return true
	default:
		return false
	}
}

// Defines values for BodyAreaStatus.
const (
	Attention BodyAreaStatus = "attention"
	Calm      BodyAreaStatus = "calm"
	Unknown   BodyAreaStatus = "unknown"
	Urgent    BodyAreaStatus = "urgent"
)

// Valid indicates whether the value is a known member of the BodyAreaStatus enum.
func (e BodyAreaStatus) Valid() bool {
	switch e {
	case Attention:
		return true
	case Calm:
		return true
	case Unknown:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for MetaMode.
const (
	Local   MetaMode = "local"
	Private MetaMode = "private"
	Public  MetaMode = "public"
)

// Valid indicates whether the value is a known member of the MetaMode enum.
func (e MetaMode) Valid() bool {
	switch e {
	case Local:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// BodyArea defines model for BodyArea.
type BodyArea struct {
	// Counts Figures behind the status, keyed by name.
	Counts  map[string]int `json:"counts"`
	Enabled bool           `json:"enabled"`
	Key     BodyAreaKey    `json:"key"`

	// Phase The release that delivers this area.
	Phase BodyAreaPhase `json:"phase"`

	// Status `unknown` means the area isn't enabled yet.
	Status BodyAreaStatus `json:"status"`
}

// BodyAreaKey defines model for BodyArea.Key.
type BodyAreaKey string

// BodyAreaPhase The release that delivers this area.
type BodyAreaPhase string

// BodyAreaStatus `unknown` means the area isn't enabled yet.
type BodyAreaStatus string

// BodyMap defines model for BodyMap.
type BodyMap struct {
	Areas []BodyArea `json:"areas"`
	AsOf  time.Time  `json:"as_of"`
}

// Contact defines model for Contact.
type Contact struct {
	// Birthday Calendar date in the user's timezone, YYYY-MM-DD.
	Birthday    *string            `json:"birthday,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Email       *string            `json:"email,omitempty"`
	HowWeMet    *string            `json:"how_we_met,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Nickname    *string            `json:"nickname,omitempty"`
	Notes       *string            `json:"notes,omitempty"`
	Phone       *string            `json:"phone,omitempty"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Version     int                `json:"version"`
}

// ContactInput defines model for ContactInput.
type ContactInput struct {
	Birthday    *string `json:"birthday,omitempty"`
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email,omitempty"`
	HowWeMet    *string `json:"how_we_met,omitempty"`
	Nickname    *string `json:"nickname,omitempty"`
	Notes       *string `json:"notes,omitempty"`
	Phone       *string `json:"phone,omitempty"`
}

// ContactList defines model for ContactList.
type ContactList struct {
	Items []Contact `json:"items"`

	// NextCursor Pass as `cursor` to get the next page. Absent on the last page.
	NextCursor *openapi_types.UUID `json:"next_cursor,omitempty"`
}

// ContactPatch Fields to change. A `null` value clears the field.
type ContactPatch map[string]*string

// Meta defines model for Meta.
type Meta struct {
	Mode MetaMode `json:"mode"`

	// Name Example: Soma
	Name string `json:"name"`

	// Version Example: 0.1.0
	Version string `json:"version"`
}

// MetaMode defines model for Meta.Mode.
type MetaMode string

// Problem RFC 9457 problem details.
type Problem struct {
	// Code Stable machine-readable error code.
	//
	// Example: request.not_found
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field validation messages keyed by JSON field name.
	Errors    *map[string]string `json:"errors,omitempty"`
	Instance  *string            `json:"instance,omitempty"`
	RequestId *string            `json:"request_id,omitempty"`

	// Status Example: 404
	Status int `json:"status"`

	// Title Example: Not Found
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// ContactId defines model for ContactId.
type ContactId = openapi_types.UUID

// ListContactsParams defines parameters for ListContacts.
type ListContactsParams struct {
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *openapi_types.UUID `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateContactParams defines parameters for UpdateContact.
type UpdateContactParams struct {
	// IfMatch The ETag of the version being edited, for example `"3"`.
	IfMatch *string `json:"If-Match,omitempty"`
}

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody = ContactInput

// UpdateContactJSONRequestBody defines body for UpdateContact for application/json ContentType.
type UpdateContactJSONRequestBody = ContactPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetBodyMap The body map
	// (GET /api/v1/bodymap)
	GetBodyMap(w http.ResponseWriter, r *http.Request)
	// GetMeta Instance information
	// (GET /api/v1/meta)
	GetMeta(w http.ResponseWriter, r *http.Request)
	// ListContacts List contacts
	// (GET /api/v1/people/contacts)
	ListContacts(w http.ResponseWriter, r *http.Request, params ListContactsParams)
	// CreateContact Create a contact
	// (POST /api/v1/people/contacts)
	CreateContact(w http.ResponseWriter, r *http.Request)
	// DeleteContact Move a contact to the trash
	// (DELETE /api/v1/people/contacts/{id})
	DeleteContact(w http.ResponseWriter, r *http.Request, id ContactId)
	// GetContact Get a contact
	// (GET /api/v1/people/contacts/{id})
	GetContact(w http.ResponseWriter, r *http.Request, id ContactId)
	// UpdateContact Update a contact
	// (PATCH /api/v1/people/contacts/{id})
	UpdateContact(w http.ResponseWriter, r *http.Request, id ContactId, params UpdateContactParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBodyMap operation middleware
func (siw *ServerInterfaceWrapper) GetBodyMap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBodyMap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeta operation middleware
func (siw *ServerInterfaceWrapper) GetMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListContacts operation middleware
func (siw *ServerInterfaceWrapper) ListContacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContactsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContacts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateContact operation middleware
func (siw *ServerInterfaceWrapper) CreateContact(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteContact operation middleware
func (siw *ServerInterfaceWrapper) DeleteContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteContact(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContact operation middleware
func (siw *ServerInterfaceWrapper) GetContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContact(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateContact operation middleware
func (siw *ServerInterfaceWrapper) UpdateContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ContactId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateContactParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateContact(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/meta", wrapper.GetMeta)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/bodymap", wrapper.GetBodyMap)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/people/contacts", wrapper.ListContacts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/people/contacts", wrapper.CreateContact)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/people/contacts/{id}", wrapper.DeleteContact)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/people/contacts/{id}", wrapper.GetContact)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/people/contacts/{id}", wrapper.UpdateContact)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type GetBodyMapRequestObject struct {
}

type GetBodyMapResponseObject interface {
	VisitGetBodyMapResponse(w http.ResponseWriter) error
}

type GetBodyMap200JSONResponse BodyMap

func (response GetBodyMap200JSONResponse) VisitGetBodyMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBodyMapdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetBodyMapdefaultApplicationProblemPlusJSONResponse) VisitGetBodyMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetaRequestObject struct {
}

type GetMetaResponseObject interface {
	VisitGetMetaResponse(w http.ResponseWriter) error
}

type GetMeta200JSONResponse Meta

func (response GetMeta200JSONResponse) VisitGetMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetadefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMetadefaultApplicationProblemPlusJSONResponse) VisitGetMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListContactsRequestObject struct {
	Params ListContactsParams
}

type ListContactsResponseObject interface {
	VisitListContactsResponse(w http.ResponseWriter) error
}

type ListContacts200JSONResponse ContactList

func (response ListContacts200JSONResponse) VisitListContactsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListContactsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListContactsdefaultApplicationProblemPlusJSONResponse) VisitListContactsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateContactRequestObject struct {
	Body *CreateContactJSONRequestBody
}

type CreateContactResponseObject interface {
	VisitCreateContactResponse(w http.ResponseWriter) error
}

type CreateContact201ResponseHeaders struct {
	ETag *string
}

type CreateContact201JSONResponse struct {
	Body    Contact
	Headers CreateContact201ResponseHeaders
}

func (response CreateContact201JSONResponse) VisitCreateContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateContactdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateContactdefaultApplicationProblemPlusJSONResponse) VisitCreateContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContactRequestObject struct {
	Id ContactId `json:"id"`
}

type DeleteContactResponseObject interface {
	VisitDeleteContactResponse(w http.ResponseWriter) error
}

type DeleteContact204Response struct {
}

func (response DeleteContact204Response) VisitDeleteContactResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteContactdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteContactdefaultApplicationProblemPlusJSONResponse) VisitDeleteContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetContactRequestObject struct {
	Id ContactId `json:"id"`
}

type GetContactResponseObject interface {
	VisitGetContactResponse(w http.ResponseWriter) error
}

type GetContact200ResponseHeaders struct {
	ETag *string
}

type GetContact200JSONResponse struct {
	Body    Contact
	Headers GetContact200ResponseHeaders
}

func (response GetContact200JSONResponse) VisitGetContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetContactdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetContactdefaultApplicationProblemPlusJSONResponse) VisitGetContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateContactRequestObject struct {
	Id     ContactId `json:"id"`
	Params UpdateContactParams
	Body   *UpdateContactJSONRequestBody
}

type UpdateContactResponseObject interface {
	VisitUpdateContactResponse(w http.ResponseWriter) error
}

type UpdateContact200ResponseHeaders struct {
	ETag *string
}

type UpdateContact200JSONResponse struct {
	Body    Contact
	Headers UpdateContact200ResponseHeaders
}

func (response UpdateContact200JSONResponse) VisitUpdateContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateContactdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateContactdefaultApplicationProblemPlusJSONResponse) VisitUpdateContactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetBodyMap The body map
	// (GET /api/v1/bodymap)
	GetBodyMap(ctx context.Context, request GetBodyMapRequestObject) (GetBodyMapResponseObject, error)
	// GetMeta Instance information
	// (GET /api/v1/meta)
	GetMeta(ctx context.Context, request GetMetaRequestObject) (GetMetaResponseObject, error)
	// ListContacts List contacts
	// (GET /api/v1/people/contacts)
	ListContacts(ctx context.Context, request ListContactsRequestObject) (ListContactsResponseObject, error)
	// CreateContact Create a contact
	// (POST /api/v1/people/contacts)
	CreateContact(ctx context.Context, request CreateContactRequestObject) (CreateContactResponseObject, error)
	// DeleteContact Move a contact to the trash
	// (DELETE /api/v1/people/contacts/{id})
	DeleteContact(ctx context.Context, request DeleteContactRequestObject) (DeleteContactResponseObject, error)
	// GetContact Get a contact
	// (GET /api/v1/people/contacts/{id})
	GetContact(ctx context.Context, request GetContactRequestObject) (GetContactResponseObject, error)
	// UpdateContact Update a contact
	// (PATCH /api/v1/people/contacts/{id})
	UpdateContact(ctx context.Context, request UpdateContactRequestObject) (UpdateContactResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBodyMap operation middleware
func (sh *strictHandler) GetBodyMap(w http.ResponseWriter, r *http.Request) {
	var request GetBodyMapRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBodyMap(ctx, request.(GetBodyMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBodyMap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBodyMapResponseObject); ok {
		if err := validResponse.VisitGetBodyMapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMeta operation middleware
func (sh *strictHandler) GetMeta(w http.ResponseWriter, r *http.Request) {
	var request GetMetaRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeta(ctx, request.(GetMetaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeta")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetaResponseObject); ok {
		if err := validResponse.VisitGetMetaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListContacts operation middleware
func (sh *strictHandler) ListContacts(w http.ResponseWriter, r *http.Request, params ListContactsParams) {
	var request ListContactsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListContacts(ctx, request.(ListContactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListContacts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListContactsResponseObject); ok {
		if err := validResponse.VisitListContactsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateContact operation middleware
func (sh *strictHandler) CreateContact(w http.ResponseWriter, r *http.Request) {
	var request CreateContactRequestObject

	var body CreateContactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateContact(ctx, request.(CreateContactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateContact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateContactResponseObject); ok {
		if err := validResponse.VisitCreateContactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteContact operation middleware
func (sh *strictHandler) DeleteContact(w http.ResponseWriter, r *http.Request, id ContactId) {
	var request DeleteContactRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteContact(ctx, request.(DeleteContactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteContact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteContactResponseObject); ok {
		if err := validResponse.VisitDeleteContactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetContact operation middleware
func (sh *strictHandler) GetContact(w http.ResponseWriter, r *http.Request, id ContactId) {
	var request GetContactRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetContact(ctx, request.(GetContactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetContactResponseObject); ok {
		if err := validResponse.VisitGetContactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateContact operation middleware
func (sh *strictHandler) UpdateContact(w http.ResponseWriter, r *http.Request, id ContactId, params UpdateContactParams) {
	var request UpdateContactRequestObject

	request.Id = id
	request.Params = params

	var body UpdateContactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateContact(ctx, request.(UpdateContactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateContact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateContactResponseObject); ok {
		if err := validResponse.VisitUpdateContactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFltbxs5Dv4rhG6BbXHjl6TpFev71OvLIodNL2i7wBV1L5ZHtEeNRppKmri+wP99QWnGHttyXrrp7n5J",
	"bA9FUuRD6qHmmuWmrIxG7R0bXbMCuUAbPr56z+f0X6DLray8NJqN2PsC4Qqtk0aDmYEvECw6U9scM/hS",
	"G48ig5mxUDsEqWFyOuudcZ8Xkz7LmMsLLDlpxa+8rBSyERuzJ2PGMuaXFX113ko9Z6vVKmMVt7xE3zj0",
	"wmjPc38q6IskZyruC5YxzUtaKQXLmMUvtbQo2MjbGrsWZ8aW3LMRq2sp0vYsuspoh8HcuTVThSV9zI32",
	"qD195FWlZM4pGoMqSvz9s6PQXHds/WBxxkbsb4NNdAfxqRu0eoPF7eA+14DWGpsBd/D29Qv46eTpM2jM",
	"gEDPpXJ9RgsbbWTsX0Ysn1sMhitrKrRexi3kpm7yyoWQZISr8y2JJghSe5yjZXsevZbz2qKDKRZSi5Bu",
	"57mvXQaXuEQB0yVQ+PubgJrpZ8w9qULNpwpFx87UGIVc08NLXNID1HXJRh9ZKTUlxaGasXUi5FQqGVzN",
	"CJnWs4xNjViyjC2MvWQZK41G+jq3ZhGw8NnUVuMyrDAlMgJRRQD6tJfxjFUFd5jGuEWF3CH4gnsQqCSB",
	"HnwhHXCLnPbbun5+xDJ2fkx/niTNxIjt25nU+lKbhZ5AiVy7EF1SDtLpHz004YMl+q65nKuSZYx7giQp",
	"ylht56gpOI3ChBerbml8DNFv9792cJOxrIXOp0RaCW9nvNqHG/kePkiPpbutDtawXa1tcGv5kr5zd2Fm",
	"W0UruMeelyGjN28trs0ab1IbaBrJ/gam0vpC8OV+ql5whVpwC+QH9TXKVe3Q/uiAvPq/0ZjBhw8fPvTO",
	"znovX/YD8LxHS6v/Nx6L65NVj/4dt/9+YAmo5Ba5R3HB/V13nzEhXaX48iK2wWtW8q+/oJ77go2Oh8PE",
	"Aiy5VLuST08SkoVZXCzwokS/I/40qViKOzTajGmZXyacPUrq1Maj25dMylaF0btaT1KCdSXuHebm1Avq",
	"pZYlVeNRttdBd9AYIrCVoa0kb7mysXEDak91VfvDLX3GlcPsBlx/Cyr/Ogj7s6Gzk92twNyQtF+kS7Sb",
	"dZu8U79sVKXapcav/iKvrTN2v3Wdc+eIT0yiwAS8gTn60MFoIVR8jn14PnWoPZjY2hR3zQOW3cqcdhAf",
	"NnNDMM6JDt5ESvbTpWul6GRqWd0+QndYCyrhaKN5wXXYHUxIxwSuuKoRcoXcxgN3RrJJ+nKGnt+z0Eoj",
	"sMtqlMm5YiQlr7gPbKSeKpknaUKL6w01fmdKfksr2ggP+0f94a3ZaVpQqyGLLqey1eG/29E9TEyzPf4p",
	"EvTqnadUQsnzQmrsWeQi/BCoL9Aa0rTZGLmPzve18RczU+vkmRJ96FDNzaOg9y4s+BCcztH2AkwIPVIE",
	"8g8lOsfn6DY8+N/v/vMmwukwJZbaea5zTFptNnohRfLxhkauY3MyPMkSHN5Lr3ag9MZ4eH0oePGHrjif",
	"mtqPporry1shFZ62RjtkMk8jaxXCMDNp3k2Qh7ev3r2H5+enfXh1hXYJlKsYdYG54jSQTL72nCl5r0Jb",
	"SkdYnmRUz2O9+QU45FwptKARhYNHk1h9kzigal77ArWncQ4FoBaVkdq7x/2xHutftZcKpCABvwTpYFpL",
	"5eHR85dve8Ojk8eAwbcmacBzH9ps6J5U9mAWGm1/rFnGlMxRx1GjGVbPTt8H4q7YiBXeV240GJgKdRyl",
	"+8bOB80iNyDZTVZDV6DodMqYqv+4PyQpUsIryUbsSX/YfxJ5aBFgM+CVHFwdDWiEKiOBn6Pfz0MMephE",
	"zAyUnCEspC9Aeree/qQGoxGaQY06rEXuYFEYh1AaUSsc6zjHxLgt0UPBrxAmzZAxgtBCJ8C1aNTCeiKK",
	"YVvnnWZ+9jP6dvTYGdWPh8MbxvT7jeeticR4Tvik2EHJq35sEzNeK39I5drHzsyfMVeXJbfLHX0sY57P",
	"HdVTm55PGdsDORu1j0fUN4PCNq1lc14lc3oekA9Sx8M8VAfVeBxpA6Ta3tRPRT4cht8x7EF/IuanjVNd",
	"zx8i9im9nRyEWB5IQHOEd0NfoakUDvJIcNzBLLzBBfWKmbTO9yEws0mHvE1gyvPL28naXoKIX75ojW/f",
	"m31s7sq+1GiXm8syJUvpt27k1gF9OsyIgsUJJ/D7m+edtIG4AXafG7hP3xFfXSKeunkLgaV21+bwIUBG",
	"1tYKO+iKcDmIr/C0qe+MVSbODtsZfxFmyGZXbM0dqHs9dMzixLnaPvaJh6/28nX00LYPteFmhG6D22dZ",
	"6uo6ZaARGwSZ1er3JzlmAnjry33zvLDS403dZHAtxSpWqEJ/4L6yESaeUkghUIdjNecapuGU9saigJk1",
	"Zegl3nJXwKP/9obPHoPReXPRiV+l826/v7wMljdo22kwqbBtRAabi/tEiZ/s7+fMXKGgzrf29CGKkbRu",
	"srSl/htTlrVNfu+0/C6RGv5hxfXnF9XP6L+9otads71o2N5imNPO0M4RwlUEPKKJ9tmTn/7xuA/vUAsw",
	"Wi03lwNbFwnxGmGsmxsE3twfQHxnEEeBsqa2z61ddl5/RQpNSicUpQmY2Vj7ztu0KUo9BxTSo/gnGF+g",
	"XUiHGRgLchbrs5WVgYgrbEYeh/YKLXDtFmgdnBwdp/jzr+Gm8QGgmaUaEG2qfSOY2lJ8K9hMmDAJb/3C",
	"O8FAHiKANuyhDdsWf0jyhe927AVs3O3Y+8Mqs7ks/itUaETT7z/2VqvfBgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
