/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instance information
         * @description Public information about this Soma instance.
         */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bodymap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The body map
         * @description Every area of life with its status, in one response. Areas whose module
         *     isn't built yet have `enabled: false` and status `unknown`.
         */
        get: operations["getBodyMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contacts
         * @description Newest first. Pass `next_cursor` back as `cursor` to get the next page.
         */
        get: operations["listContacts"];
        put?: never;
        /** Create a contact */
        post: operations["createContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a contact */
        get: operations["getContact"];
        put?: never;
        post?: never;
        /**
         * Move a contact to the trash
         * @description The contact is hidden and can be restored from the trash (X-07) once that exists.
         */
        delete: operations["deleteContact"];
        options?: never;
        head?: never;
        /**
         * Update a contact
         * @description JSON Merge Patch (RFC 7396). Send only the fields to change. `null`
         *     clears a field. The request must carry `If-Match` with the `ETag` of
         *     the version being edited; otherwise, or if that version is stale, the
         *     server answers 412.
         */
        patch: operations["updateContact"];
        trace?: never;
    };
    "/api/v1/journal/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your journal entries
         * @description Only your own entries are listed; other members never see them.
         */
        get: operations["listJournalEntries"];
        put?: never;
        /** Write an entry */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an entry */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        /** Move an entry to the trash */
        delete: operations["deleteJournalEntry"];
        options?: never;
        head?: never;
        /**
         * Edit an entry
         * @description JSON Merge Patch. Send only the fields to change; `null` clears one.
         *     Requires `If-Match` with the entry's current ETag; otherwise 412.
         */
        patch: operations["updateJournalEntry"];
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: operations["listTasks"];
        put?: never;
        /** Add a task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        /** Move a task to the trash */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * Edit a task
         * @description JSON Merge Patch with `If-Match`, as for journal entries.
         */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/api/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a task done */
        post: operations["completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a done task open again */
        post: operations["reopenTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read your Self profile */
        get: operations["getSelfProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit your Self profile
         * @description JSON Merge Patch with `If-Match`, as for journal entries.
         */
        patch: operations["updateSelfProfile"];
        trace?: never;
    };
    "/api/v1/money/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Currencies you can use, with their minor-unit digits */
        get: operations["listCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the money settings */
        get: operations["getMoneySettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the base currency
         * @description JSON Merge Patch with `If-Match`. Totals and budgets are shown in the base currency.
         */
        patch: operations["updateMoneySettings"];
        trace?: never;
    };
    "/api/v1/money/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts with their balances */
        get: operations["listAccounts"];
        put?: never;
        /** Add an account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /** Move an account to the trash */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /**
         * Edit an account
         * @description JSON Merge Patch with `If-Match`. The currency of an account can't change.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/money/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories (a two-level tree) */
        get: operations["listCategories"];
        put?: never;
        /** Add a category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions, newest first */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Record an income, an expense or a transfer
         * @description Amounts are positive; the kind sets the sign. A transfer creates two
         *     linked rows, and both accounts must use the same currency.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a transaction */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Move a transaction to the trash
         * @description A transfer moves both of its sides to the trash together.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Edit a transaction
         * @description JSON Merge Patch with `If-Match`. Editable: `amount_minor` (positive),
         *     `occurred_on`, `category_id`, `payee`, `notes`. Transfers and the kind
         *     can't be edited; delete and record again instead.
         */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/api/v1/money/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budgets and spending for a month */
        get: operations["getBudgets"];
        /**
         * Set a category's budget for a month
         * @description An amount of 0 removes the budget.
         */
        put: operations["setBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The latest exchange rate per currency */
        get: operations["listRates"];
        /**
         * Set the exchange rate for a currency on a day
         * @description One unit of the currency equals `rate_e8 / 10^8` base-currency major units.
         */
        put: operations["setRate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/money/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth and the month's totals, in the base currency */
        get: operations["getMoneySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JournalEntry: {
            /** Format: uuid */
            id: string;
            /** @description The day the entry is about, YYYY-MM-DD. */
            entry_date: string;
            title?: string;
            body: string;
            /** @description How the day felt, from 1 (low) to 5 (high). */
            mood?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        JournalEntryInput: {
            entry_date: string;
            title?: string;
            body: string;
            mood?: number;
        };
        JournalEntryList: {
            items: components["schemas"]["JournalEntry"][];
            /** Format: uuid */
            next_cursor?: string;
        };
        Task: {
            /** Format: uuid */
            id: string;
            title: string;
            notes?: string;
            due_on?: string;
            completed: boolean;
            /** Format: date-time */
            completed_at?: string;
            /** @description Open and due before today. */
            overdue: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        TaskInput: {
            title: string;
            notes?: string;
            due_on?: string;
        };
        TaskList: {
            items: components["schemas"]["Task"][];
            /** Format: uuid */
            next_cursor?: string;
        };
        SelfProfile: {
            preferred_name?: string;
            birth_date?: string;
            /** @description What matters most to you, in your own words. */
            core_values?: string;
            bio?: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        /** @description Fields to change. A null value clears the field. Unknown fields are refused. */
        MergePatch: {
            [key: string]: unknown;
        };
        Currency: {
            code: string;
            /** @description Digits after the decimal point, for display and input. */
            digits: number;
        };
        CurrencyList: {
            items: components["schemas"]["Currency"][];
        };
        MoneySettings: {
            base_currency: string;
            version: number;
            /** Format: date-time */
            updated_at: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "cash" | "bank" | "credit_card" | "e_wallet" | "loan" | "investment";
            currency: string;
            /** @description Balance before the first recorded transaction, in minor units. A loan is entered as a negative amount. */
            opening_minor: number;
            opened_on: string;
            /** @description Opening balance plus every transaction, in minor units. */
            balance_minor: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        AccountInput: {
            name: string;
            /** @enum {string} */
            kind: "cash" | "bank" | "credit_card" | "e_wallet" | "loan" | "investment";
            currency: string;
            /** @default 0 */
            opening_minor: number;
            opened_on: string;
        };
        AccountList: {
            items: components["schemas"]["Account"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string;
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
        };
        CategoryInput: {
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
            /** Format: uuid */
            parent_id?: string;
        };
        CategoryList: {
            items: components["schemas"]["Category"][];
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** @enum {string} */
            kind: "income" | "expense" | "transfer_in" | "transfer_out" | "adjustment";
            /** @description Signed: income and transfers in are positive, expenses and transfers out negative. */
            amount_minor: number;
            occurred_on: string;
            /** Format: uuid */
            category_id?: string;
            payee?: string;
            notes?: string;
            /**
             * Format: uuid
             * @description Shared by the two sides of a transfer.
             */
            transfer_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        TransactionInput: {
            /** @enum {string} */
            kind: "income" | "expense" | "transfer";
            /** Format: uuid */
            account_id: string;
            /**
             * Format: uuid
             * @description The receiving account, for a transfer.
             */
            to_account_id?: string;
            amount_minor: number;
            occurred_on: string;
            /** Format: uuid */
            category_id?: string;
            payee?: string;
            notes?: string;
        };
        TransactionList: {
            items: components["schemas"]["Transaction"][];
            next_cursor?: string;
        };
        BudgetLine: {
            /** Format: uuid */
            category_id: string;
            name: string;
            /** Format: uuid */
            parent_id?: string;
            /** @description The budget for the month, in the base currency. 0 means none set. */
            budget_minor: number;
            /** @description Expenses in this category and its subcategories, in the base currency. */
            spent_minor: number;
        };
        BudgetMonth: {
            month: string;
            base_currency: string;
            items: components["schemas"]["BudgetLine"][];
        };
        BudgetInput: {
            /** Format: uuid */
            category_id: string;
            /** @description Any day in the month. */
            month: string;
            amount_minor: number;
        };
        Rate: {
            currency: string;
            rate_on: string;
            /** @description One unit of the currency, in base-currency major units, times 10^8. */
            rate_e8: number;
        };
        RateInput: {
            currency: string;
            rate_on: string;
            rate_e8: number;
        };
        RateList: {
            items: components["schemas"]["Rate"][];
        };
        MoneySummary: {
            month: string;
            base_currency: string;
            /** @description All account balances in the base currency. Accounts whose currency has no rate are left out and listed in missing_rates. */
            net_worth_minor: number;
            income_minor: number;
            /** @description Positive total of this month's expenses, in the base currency. */
            expense_minor: number;
            overspent_categories: number;
            accounts: {
                /** Format: uuid */
                id: string;
                name: string;
                currency: string;
                balance_minor: number;
                /** @description The balance in the base currency, when a rate is known. */
                base_minor?: number;
            }[];
            missing_rates: string[];
        };
        Meta: {
            /** @example Soma */
            name: string;
            /** @example 0.1.0 */
            version: string;
            /** @enum {string} */
            mode: "local" | "private" | "public";
        };
        Contact: {
            /** Format: uuid */
            id: string;
            display_name: string;
            nickname?: string;
            email?: string;
            phone?: string;
            /** @description Calendar date in the user's timezone, YYYY-MM-DD. */
            birthday?: string;
            how_we_met?: string;
            notes?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        ContactInput: {
            display_name: string;
            nickname?: string;
            email?: string;
            phone?: string;
            birthday?: string;
            how_we_met?: string;
            notes?: string;
        };
        /** @description Fields to change. A `null` value clears the field. */
        ContactPatch: {
            [key: string]: string | null;
        };
        BodyMap: {
            /** Format: date-time */
            as_of: string;
            areas: components["schemas"]["BodyArea"][];
        };
        BodyArea: {
            /** @enum {string} */
            key: "mind" | "self" | "responsibilities" | "heart" | "body" | "work" | "money" | "growth" | "journeys" | "home" | "papers";
            /**
             * @description The release that delivers this area.
             * @enum {string}
             */
            phase: "P1" | "P2" | "P3";
            /**
             * @description `unknown` means the area isn't enabled yet.
             * @enum {string}
             */
            status: "calm" | "attention" | "urgent" | "unknown";
            enabled: boolean;
            /** @description Figures behind the status, keyed by name. */
            counts: {
                [key: string]: number;
            };
        };
        ContactList: {
            items: components["schemas"]["Contact"][];
            /**
             * Format: uuid
             * @description Pass as `cursor` to get the next page. Absent on the last page.
             */
            next_cursor?: string;
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Not Found */
            title: string;
            /** @example 404 */
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Stable machine-readable error code.
             * @example request.not_found
             */
            code: string;
            request_id?: string;
            /** @description Per-field validation messages keyed by JSON field name. */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ResourceId: string;
        /** @description The ETag of the version being edited, for example "3". */
        IfMatch: string;
        ContactId: string;
    };
    requestBodies: never;
    headers: {
        /** @description The version of the resource, quoted, for use in `If-Match`. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBodyMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The body map. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMap"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listContacts: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of contacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactInput"];
            };
        };
        responses: {
            /** @description The created contact. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ContactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contact. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ContactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moved to the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateContact: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example `"3"`. */
                "If-Match"?: string;
            };
            path: {
                id: components["parameters"]["ContactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactPatch"];
            };
        };
        responses: {
            /** @description The updated contact. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries, newest saved first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntryList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryInput"];
            };
        };
        responses: {
            /** @description The saved entry. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moved to the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated entry. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                open_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tasks, newest saved first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskInput"];
            };
        };
        responses: {
            /** @description The new task. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moved to the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated task. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task, now done. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    reopenTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task, open again. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSelfProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfProfile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSelfProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated profile. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfProfile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The currency list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMoneySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneySettings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMoneySettings: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated settings. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneySettings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInput"];
            };
        };
        responses: {
            /** @description The new account. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moved to the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description The new category. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Pass `next_cursor` back to get the next page. */
                cursor?: string;
                account_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description The recorded transaction (for a transfer, the outgoing side). */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moved to the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the version being edited, for example "3". */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePatch"];
            };
        };
        responses: {
            /** @description The updated transaction. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBudgets: {
        parameters: {
            query?: {
                /** @description Any day in the month, YYYY-MM-DD. Defaults to this month. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month's budget lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetMonth"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetInput"];
            };
        };
        responses: {
            /** @description The budget line after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetLine"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateInput"];
            };
        };
        responses: {
            /** @description The stored rate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMoneySummary: {
        parameters: {
            query?: {
                /** @description Any day in the month, YYYY-MM-DD. Defaults to this month. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoneySummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
