/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instance information
         * @description Public information about this Soma instance.
         */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /** @example Soma */
            name: string;
            /** @example 0.1.0 */
            version: string;
            /** @enum {string} */
            mode: "local" | "private" | "public";
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Not Found */
            title: string;
            /** @example 404 */
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Stable machine-readable error code.
             * @example request.not_found
             */
            code: string;
            request_id?: string;
            /** @description Per-field validation messages keyed by JSON field name. */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
