// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTask = `-- name: GetTask :one
SELECT t.id, t.title, t.notes, t.due_on, t.completed_at, e.created_at, e.updated_at, e.version
FROM tasks t
JOIN entities e ON e.id = t.id
WHERE t.id = $1 AND t.space_id = $2 AND e.deleted_at IS NULL
`

type GetTaskParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

type GetTaskRow struct {
	ID          uuid.UUID
	Title       string
	Notes       *string
	DueOn       *time.Time
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.SpaceID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.DueOn,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (id, space_id, title, notes, due_on)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTaskParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
	Title   string
	Notes   *string
	DueOn   *time.Time
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.ID,
		arg.SpaceID,
		arg.Title,
		arg.Notes,
		arg.DueOn,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.title, t.notes, t.due_on, t.completed_at, e.created_at, e.updated_at, e.version
FROM tasks t
JOIN entities e ON e.id = t.id
WHERE t.space_id = $1 AND e.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.id < $2::uuid)
  AND ($3::boolean = false OR t.completed_at IS NULL)
ORDER BY t.id DESC
LIMIT $4
`

type ListTasksParams struct {
	SpaceID  uuid.UUID
	Before   *uuid.UUID
	OnlyOpen bool
	RowLimit int32
}

type ListTasksRow struct {
	ID          uuid.UUID
	Title       string
	Notes       *string
	DueOn       *time.Time
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Newest saved first, so the cursor (the last ID seen) keeps paging stable.
// The browser sorts open tasks by due date.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.SpaceID,
		arg.Before,
		arg.OnlyOpen,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.DueOn,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskCompleted = `-- name: SetTaskCompleted :exec
UPDATE tasks
SET completed_at = $1
WHERE id = $2 AND space_id = $3
`

type SetTaskCompletedParams struct {
	CompletedAt *time.Time
	ID          uuid.UUID
	SpaceID     uuid.UUID
}

func (q *Queries) SetTaskCompleted(ctx context.Context, arg SetTaskCompletedParams) error {
	_, err := q.db.Exec(ctx, setTaskCompleted, arg.CompletedAt, arg.ID, arg.SpaceID)
	return err
}

const taskCounts = `-- name: TaskCounts :one
SELECT
  count(*) FILTER (WHERE t.completed_at IS NULL AND t.due_on < $1::date)::bigint AS overdue,
  count(*) FILTER (WHERE t.completed_at IS NULL AND t.due_on = $1::date)::bigint AS due_today,
  count(*) FILTER (WHERE t.completed_at IS NULL AND t.due_on < $1::date - 3)::bigint AS overdue_long
FROM tasks t
JOIN entities e ON e.id = t.id
WHERE t.space_id = $2 AND e.deleted_at IS NULL
`

type TaskCountsParams struct {
	Today   time.Time
	SpaceID uuid.UUID
}

type TaskCountsRow struct {
	Overdue     int64
	DueToday    int64
	OverdueLong int64
}

// Open tasks overdue (due before today) and due today, for the Responsibilities area.
func (q *Queries) TaskCounts(ctx context.Context, arg TaskCountsParams) (TaskCountsRow, error) {
	row := q.db.QueryRow(ctx, taskCounts, arg.Today, arg.SpaceID)
	var i TaskCountsRow
	err := row.Scan(&i.Overdue, &i.DueToday, &i.OverdueLong)
	return i, err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = $1, notes = $2, due_on = $3
WHERE id = $4 AND space_id = $5
`

type UpdateTaskParams struct {
	Title   string
	Notes   *string
	DueOn   *time.Time
	ID      uuid.UUID
	SpaceID uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Notes,
		arg.DueOn,
		arg.ID,
		arg.SpaceID,
	)
	return err
}
