// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM space_members WHERE space_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	SpaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.SpaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}
