// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bootstrap.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSelfProfile = `-- name: InsertSelfProfile :exec
INSERT INTO self_profiles (space_id, updated_at)
VALUES ($1, $2)
ON CONFLICT (space_id) DO NOTHING
`

type InsertSelfProfileParams struct {
	SpaceID uuid.UUID
	Now     time.Time
}

// Every space has one Self profile, created with the space. Idempotent.
func (q *Queries) InsertSelfProfile(ctx context.Context, arg InsertSelfProfileParams) error {
	_, err := q.db.Exec(ctx, insertSelfProfile, arg.SpaceID, arg.Now)
	return err
}

const insertSpace = `-- name: InsertSpace :exec
INSERT INTO spaces (id, name, created_by, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertSpaceParams struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	Now       time.Time
}

// Plain INSERT on purpose: ON CONFLICT would also apply the space's read
// policy to the new row, which fails before the owner is a member (ADR-014).
func (q *Queries) InsertSpace(ctx context.Context, arg InsertSpaceParams) error {
	_, err := q.db.Exec(ctx, insertSpace,
		arg.ID,
		arg.Name,
		arg.CreatedBy,
		arg.Now,
	)
	return err
}

const insertSpaceMember = `-- name: InsertSpaceMember :exec
INSERT INTO space_members (space_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertSpaceMemberParams struct {
	SpaceID uuid.UUID
	UserID  uuid.UUID
	Role    string
	Now     time.Time
}

func (q *Queries) InsertSpaceMember(ctx context.Context, arg InsertSpaceMemberParams) error {
	_, err := q.db.Exec(ctx, insertSpaceMember,
		arg.SpaceID,
		arg.UserID,
		arg.Role,
		arg.Now,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, display_name, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type UpsertUserParams struct {
	ID          uuid.UUID
	DisplayName string
	Now         time.Time
}

// users has no row-level security, so an upsert is safe here.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.DisplayName, arg.Now)
	return err
}
