// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpEntityVersion = `-- name: BumpEntityVersion :one
UPDATE entities
SET version = version + 1, updated_at = $1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING version
`

type BumpEntityVersionParams struct {
	Now             time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

// Returns no rows when the expected version is stale, which the caller maps to 412.
func (q *Queries) BumpEntityVersion(ctx context.Context, arg BumpEntityVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpEntityVersion, arg.Now, arg.ID, arg.ExpectedVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const insertEntity = `-- name: InsertEntity :one
INSERT INTO entities (space_id, kind, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, version
`

type InsertEntityParams struct {
	SpaceID   uuid.UUID
	Kind      string
	CreatedBy uuid.UUID
	Now       time.Time
}

type InsertEntityRow struct {
	ID      uuid.UUID
	Version int32
}

func (q *Queries) InsertEntity(ctx context.Context, arg InsertEntityParams) (InsertEntityRow, error) {
	row := q.db.QueryRow(ctx, insertEntity,
		arg.SpaceID,
		arg.Kind,
		arg.CreatedBy,
		arg.Now,
	)
	var i InsertEntityRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const softDeleteEntity = `-- name: SoftDeleteEntity :execrows
UPDATE entities
SET deleted_at = $1, updated_at = $1, version = version + 1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteEntityParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) SoftDeleteEntity(ctx context.Context, arg SoftDeleteEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEntity, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
