// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getContact = `-- name: GetContact :one
SELECT c.id, c.display_name, c.nickname, c.email, c.phone, c.birthday, c.how_we_met, c.notes,
       e.created_at, e.updated_at, e.version
FROM people_contacts c
JOIN entities e ON e.id = c.id
WHERE c.id = $1 AND c.space_id = $2 AND e.deleted_at IS NULL
`

type GetContactParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

type GetContactRow struct {
	ID          uuid.UUID
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    *time.Time
	HowWeMet    *string
	Notes       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.SpaceID)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Nickname,
		&i.Email,
		&i.Phone,
		&i.Birthday,
		&i.HowWeMet,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO people_contacts (id, space_id, display_name, nickname, email, phone, birthday, how_we_met, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertContactParams struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    *time.Time
	HowWeMet    *string
	Notes       *string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.Exec(ctx, insertContact,
		arg.ID,
		arg.SpaceID,
		arg.DisplayName,
		arg.Nickname,
		arg.Email,
		arg.Phone,
		arg.Birthday,
		arg.HowWeMet,
		arg.Notes,
	)
	return err
}

const listBirthdays = `-- name: ListBirthdays :many
SELECT c.birthday
FROM people_contacts c
JOIN entities e ON e.id = c.id
WHERE c.space_id = $1
  AND e.deleted_at IS NULL
  AND c.birthday IS NOT NULL
`

func (q *Queries) ListBirthdays(ctx context.Context, spaceID uuid.UUID) ([]*time.Time, error) {
	rows, err := q.db.Query(ctx, listBirthdays, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*time.Time
	for rows.Next() {
		var birthday *time.Time
		if err := rows.Scan(&birthday); err != nil {
			return nil, err
		}
		items = append(items, birthday)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.display_name, c.nickname, c.email, c.phone, c.birthday, c.how_we_met, c.notes,
       e.created_at, e.updated_at, e.version
FROM people_contacts c
JOIN entities e ON e.id = c.id
WHERE c.space_id = $1
  AND e.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.id < $2::uuid)
ORDER BY c.id DESC
LIMIT $3
`

type ListContactsParams struct {
	SpaceID  uuid.UUID
	Before   *uuid.UUID
	RowLimit int32
}

type ListContactsRow struct {
	ID          uuid.UUID
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    *time.Time
	HowWeMet    *string
	Notes       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Newest first. UUIDv7 keys are time-ordered, so the cursor is the last ID seen.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.SpaceID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Nickname,
			&i.Email,
			&i.Phone,
			&i.Birthday,
			&i.HowWeMet,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :exec
UPDATE people_contacts
SET display_name = $1,
    nickname = $2,
    email = $3,
    phone = $4,
    birthday = $5,
    how_we_met = $6,
    notes = $7
WHERE id = $8 AND space_id = $9
`

type UpdateContactParams struct {
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    *time.Time
	HowWeMet    *string
	Notes       *string
	ID          uuid.UUID
	SpaceID     uuid.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) error {
	_, err := q.db.Exec(ctx, updateContact,
		arg.DisplayName,
		arg.Nickname,
		arg.Email,
		arg.Phone,
		arg.Birthday,
		arg.HowWeMet,
		arg.Notes,
		arg.ID,
		arg.SpaceID,
	)
	return err
}
