// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEntry = `-- name: GetEntry :one
SELECT j.id, j.entry_date, j.title, j.body, j.mood, e.created_at, e.updated_at, e.version
FROM journal_entries j
JOIN entities e ON e.id = j.id
WHERE j.id = $1 AND j.space_id = $2 AND j.author_id = $3 AND e.deleted_at IS NULL
`

type GetEntryParams struct {
	ID       uuid.UUID
	SpaceID  uuid.UUID
	AuthorID uuid.UUID
}

type GetEntryRow struct {
	ID        uuid.UUID
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (GetEntryRow, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.ID, arg.SpaceID, arg.AuthorID)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.EntryDate,
		&i.Title,
		&i.Body,
		&i.Mood,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO journal_entries (id, space_id, author_id, entry_date, title, body, mood)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEntryParams struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	AuthorID  uuid.UUID
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.SpaceID,
		arg.AuthorID,
		arg.EntryDate,
		arg.Title,
		arg.Body,
		arg.Mood,
	)
	return err
}

const lastEntryStats = `-- name: LastEntryStats :one
SELECT COALESCE(max(j.entry_date), '0001-01-01'::date)::date AS last_entry_date, count(*)::bigint AS entries
FROM journal_entries j
JOIN entities e ON e.id = j.id
WHERE j.space_id = $1 AND j.author_id = $2 AND e.deleted_at IS NULL
`

type LastEntryStatsParams struct {
	SpaceID  uuid.UUID
	AuthorID uuid.UUID
}

type LastEntryStatsRow struct {
	LastEntryDate time.Time
	Entries       int64
}

// The newest entry date and how many entries exist, for the Mind area. With no
// entries the date is a placeholder; callers check the count first.
func (q *Queries) LastEntryStats(ctx context.Context, arg LastEntryStatsParams) (LastEntryStatsRow, error) {
	row := q.db.QueryRow(ctx, lastEntryStats, arg.SpaceID, arg.AuthorID)
	var i LastEntryStatsRow
	err := row.Scan(&i.LastEntryDate, &i.Entries)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT j.id, j.entry_date, j.title, j.body, j.mood, e.created_at, e.updated_at, e.version
FROM journal_entries j
JOIN entities e ON e.id = j.id
WHERE j.space_id = $1 AND j.author_id = $2 AND e.deleted_at IS NULL
  AND ($3::uuid IS NULL OR j.id < $3::uuid)
ORDER BY j.id DESC
LIMIT $4
`

type ListEntriesParams struct {
	SpaceID  uuid.UUID
	AuthorID uuid.UUID
	Before   *uuid.UUID
	RowLimit int32
}

type ListEntriesRow struct {
	ID        uuid.UUID
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// Newest saved first. UUIDv7 keys are time-ordered, so the cursor is the last ID seen.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.SpaceID,
		arg.AuthorID,
		arg.Before,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryDate,
			&i.Title,
			&i.Body,
			&i.Mood,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE journal_entries
SET entry_date = $1, title = $2, body = $3, mood = $4
WHERE id = $5 AND space_id = $6 AND author_id = $7
`

type UpdateEntryParams struct {
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
	ID        uuid.UUID
	SpaceID   uuid.UUID
	AuthorID  uuid.UUID
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.Exec(ctx, updateEntry,
		arg.EntryDate,
		arg.Title,
		arg.Body,
		arg.Mood,
		arg.ID,
		arg.SpaceID,
		arg.AuthorID,
	)
	return err
}
