// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Entity struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	Kind      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	Version   int32
}

type JournalEntry struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	AuthorID  uuid.UUID
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
}

type PeopleContact struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    *time.Time
	HowWeMet    *string
	Notes       *string
}

type SelfProfile struct {
	SpaceID       uuid.UUID
	PreferredName *string
	BirthDate     *time.Time
	CoreValues    *string
	Bio           *string
	UpdatedAt     time.Time
	Version       int32
}

type Space struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type SpaceMember struct {
	SpaceID   uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Task struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	Title       string
	Notes       *string
	DueOn       *time.Time
	CompletedAt *time.Time
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}
