// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSelfProfile = `-- name: GetSelfProfile :one
SELECT preferred_name, birth_date, core_values, bio, updated_at, version
FROM self_profiles
WHERE space_id = $1
`

type GetSelfProfileRow struct {
	PreferredName *string
	BirthDate     *time.Time
	CoreValues    *string
	Bio           *string
	UpdatedAt     time.Time
	Version       int32
}

func (q *Queries) GetSelfProfile(ctx context.Context, spaceID uuid.UUID) (GetSelfProfileRow, error) {
	row := q.db.QueryRow(ctx, getSelfProfile, spaceID)
	var i GetSelfProfileRow
	err := row.Scan(
		&i.PreferredName,
		&i.BirthDate,
		&i.CoreValues,
		&i.Bio,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateSelfProfile = `-- name: UpdateSelfProfile :one
UPDATE self_profiles
SET preferred_name = $1,
    birth_date = $2,
    core_values = $3,
    bio = $4,
    updated_at = $5,
    version = version + 1
WHERE space_id = $6 AND version = $7
RETURNING version
`

type UpdateSelfProfileParams struct {
	PreferredName   *string
	BirthDate       *time.Time
	CoreValues      *string
	Bio             *string
	Now             time.Time
	SpaceID         uuid.UUID
	ExpectedVersion int32
}

// Returns no rows when the expected version is stale, which the caller maps to 412.
func (q *Queries) UpdateSelfProfile(ctx context.Context, arg UpdateSelfProfileParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateSelfProfile,
		arg.PreferredName,
		arg.BirthDate,
		arg.CoreValues,
		arg.Bio,
		arg.Now,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
