// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Entity struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	Kind      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
	Version   int32
}

type FinAccount struct {
	ID           uuid.UUID
	SpaceID      uuid.UUID
	Name         string
	Kind         string
	Currency     string
	OpeningMinor int64
	OpenedOn     time.Time
}

type FinBudget struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	CategoryID  uuid.UUID
	Month       time.Time
	AmountMinor int64
}

type FinCategory struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	Kind      string
	CreatedAt time.Time
}

type FinRate struct {
	SpaceID  uuid.UUID
	Currency string
	RateOn   time.Time
	RateE8   int64
}

type FinSetting struct {
	SpaceID      uuid.UUID
	BaseCurrency string
	UpdatedAt    time.Time
	Version      int32
}

type FinTransaction struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	OccurredOn  time.Time
	CategoryID  *uuid.UUID
	Payee       *string
	Notes       *string
	TransferID  *uuid.UUID
}

type JournalEntry struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	AuthorID  uuid.UUID
	EntryDate time.Time
	Title     *string
	Body      string
	Mood      pgtype.Int2
}

type PeopleContact struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	DisplayName string
	Nickname    *string
	Email       *string
	Phone       *string
	Birthday    pgtype.Date
	HowWeMet    *string
	Notes       *string
}

type SelfProfile struct {
	SpaceID       uuid.UUID
	PreferredName *string
	BirthDate     pgtype.Date
	CoreValues    *string
	Bio           *string
	UpdatedAt     time.Time
	Version       int32
}

type Space struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type SpaceMember struct {
	SpaceID   uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Task struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	Title       string
	Notes       *string
	DueOn       pgtype.Date
	CompletedAt pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}
