// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: money.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalances = `-- name: AccountBalances :many
SELECT a.id, (a.opening_minor + COALESCE(SUM(CASE WHEN tx_e.id IS NULL THEN 0 ELSE t.amount_minor END), 0))::bigint AS balance_minor
FROM fin_accounts a
JOIN entities ae ON ae.id = a.id AND ae.deleted_at IS NULL
LEFT JOIN fin_transactions t ON t.account_id = a.id
LEFT JOIN entities tx_e ON tx_e.id = t.id AND tx_e.deleted_at IS NULL
WHERE a.space_id = $1
GROUP BY a.id, a.opening_minor
`

type AccountBalancesRow struct {
	ID           uuid.UUID
	BalanceMinor int64
}

// Opening balance plus every live transaction on the account. Deleted rows are
// excluded by the LEFT JOIN on entities, so they contribute nothing.
func (q *Queries) AccountBalances(ctx context.Context, spaceID uuid.UUID) ([]AccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, accountBalances, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBalancesRow
	for rows.Next() {
		var i AccountBalancesRow
		if err := rows.Scan(&i.ID, &i.BalanceMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCategories = `-- name: CountCategories :one
SELECT count(*)::bigint AS total
FROM fin_categories
WHERE space_id = $1
`

func (q *Queries) CountCategories(ctx context.Context, spaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, spaceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM fin_budgets
WHERE space_id = $1 AND category_id = $2 AND month = $3
`

type DeleteBudgetParams struct {
	SpaceID    uuid.UUID
	CategoryID uuid.UUID
	Month      time.Time
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudget, arg.SpaceID, arg.CategoryID, arg.Month)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT a.id, a.name, a.kind, a.currency, a.opening_minor, a.opened_on, e.created_at, e.updated_at, e.version
FROM fin_accounts a
JOIN entities e ON e.id = a.id
WHERE a.id = $1 AND a.space_id = $2 AND e.deleted_at IS NULL
`

type GetAccountParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

type GetAccountRow struct {
	ID           uuid.UUID
	Name         string
	Kind         string
	Currency     string
	OpeningMinor int64
	OpenedOn     time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Version      int32
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.SpaceID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Currency,
		&i.OpeningMinor,
		&i.OpenedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, name, kind
FROM fin_categories
WHERE id = $1 AND space_id = $2
`

type GetCategoryParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

type GetCategoryRow struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
	Name     string
	Kind     string
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.SpaceID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT base_currency, updated_at, version
FROM fin_settings
WHERE space_id = $1
`

type GetSettingsRow struct {
	BaseCurrency string
	UpdatedAt    time.Time
	Version      int32
}

func (q *Queries) GetSettings(ctx context.Context, spaceID uuid.UUID) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings, spaceID)
	var i GetSettingsRow
	err := row.Scan(&i.BaseCurrency, &i.UpdatedAt, &i.Version)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.account_id, t.kind, t.amount_minor, t.occurred_on, t.category_id, t.payee, t.notes, t.transfer_id,
       e.created_at, e.updated_at, e.version
FROM fin_transactions t
JOIN entities e ON e.id = t.id
WHERE t.id = $1 AND t.space_id = $2 AND e.deleted_at IS NULL
`

type GetTransactionParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

type GetTransactionRow struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	OccurredOn  time.Time
	CategoryID  *uuid.UUID
	Payee       *string
	Notes       *string
	TransferID  *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.SpaceID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.AmountMinor,
		&i.OccurredOn,
		&i.CategoryID,
		&i.Payee,
		&i.Notes,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO fin_accounts (id, space_id, name, kind, currency, opening_minor, opened_on)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAccountParams struct {
	ID           uuid.UUID
	SpaceID      uuid.UUID
	Name         string
	Kind         string
	Currency     string
	OpeningMinor int64
	OpenedOn     time.Time
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.SpaceID,
		arg.Name,
		arg.Kind,
		arg.Currency,
		arg.OpeningMinor,
		arg.OpenedOn,
	)
	return err
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO fin_categories (id, space_id, parent_id, name, kind, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCategoryParams struct {
	ID       uuid.UUID
	SpaceID  uuid.UUID
	ParentID *uuid.UUID
	Name     string
	Kind     string
	Now      time.Time
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory,
		arg.ID,
		arg.SpaceID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.Now,
	)
	return err
}

const insertSettings = `-- name: InsertSettings :exec
INSERT INTO fin_settings (space_id, updated_at)
VALUES ($1, $2)
ON CONFLICT (space_id) DO NOTHING
`

type InsertSettingsParams struct {
	SpaceID uuid.UUID
	Now     time.Time
}

func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) error {
	_, err := q.db.Exec(ctx, insertSettings, arg.SpaceID, arg.Now)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO fin_transactions (id, space_id, account_id, kind, amount_minor, occurred_on, category_id, payee, notes, transfer_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTransactionParams struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	OccurredOn  time.Time
	CategoryID  *uuid.UUID
	Payee       *string
	Notes       *string
	TransferID  *uuid.UUID
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.SpaceID,
		arg.AccountID,
		arg.Kind,
		arg.AmountMinor,
		arg.OccurredOn,
		arg.CategoryID,
		arg.Payee,
		arg.Notes,
		arg.TransferID,
	)
	return err
}

const latestRates = `-- name: LatestRates :many
SELECT DISTINCT ON (currency) currency, rate_on, rate_e8
FROM fin_rates
WHERE space_id = $1 AND rate_on <= $2
ORDER BY currency, rate_on DESC
`

type LatestRatesParams struct {
	SpaceID uuid.UUID
	AsOf    time.Time
}

type LatestRatesRow struct {
	Currency string
	RateOn   time.Time
	RateE8   int64
}

// The newest rate on or before the given day, per currency.
func (q *Queries) LatestRates(ctx context.Context, arg LatestRatesParams) ([]LatestRatesRow, error) {
	rows, err := q.db.Query(ctx, latestRates, arg.SpaceID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRatesRow
	for rows.Next() {
		var i LatestRatesRow
		if err := rows.Scan(&i.Currency, &i.RateOn, &i.RateE8); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.name, a.kind, a.currency, a.opening_minor, a.opened_on, e.created_at, e.updated_at, e.version
FROM fin_accounts a
JOIN entities e ON e.id = a.id
WHERE a.space_id = $1 AND e.deleted_at IS NULL
ORDER BY a.opened_on, a.name
`

type ListAccountsRow struct {
	ID           uuid.UUID
	Name         string
	Kind         string
	Currency     string
	OpeningMinor int64
	OpenedOn     time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Version      int32
}

func (q *Queries) ListAccounts(ctx context.Context, spaceID uuid.UUID) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Currency,
			&i.OpeningMinor,
			&i.OpenedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, name, kind
FROM fin_categories
WHERE space_id = $1
ORDER BY parent_id NULLS FIRST, name
`

type ListCategoriesRow struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
	Name     string
	Kind     string
}

func (q *Queries) ListCategories(ctx context.Context, spaceID uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.account_id, t.kind, t.amount_minor, t.occurred_on, t.category_id, t.payee, t.notes, t.transfer_id,
       e.created_at, e.updated_at, e.version
FROM fin_transactions t
JOIN entities e ON e.id = t.id
WHERE t.space_id = $1 AND e.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.account_id = $2::uuid)
  AND ($3::date IS NULL
       OR (t.occurred_on, t.id) < ($3::date, $4::uuid))
ORDER BY t.occurred_on DESC, t.id DESC
LIMIT $5
`

type ListTransactionsParams struct {
	SpaceID    uuid.UUID
	AccountID  *uuid.UUID
	BeforeDate pgtype.Date
	BeforeID   *uuid.UUID
	RowLimit   int32
}

type ListTransactionsRow struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	AmountMinor int64
	OccurredOn  time.Time
	CategoryID  *uuid.UUID
	Payee       *string
	Notes       *string
	TransferID  *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

// Newest first. The cursor is the (date, ID) of the last row seen.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.SpaceID,
		arg.AccountID,
		arg.BeforeDate,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.AmountMinor,
			&i.OccurredOn,
			&i.CategoryID,
			&i.Payee,
			&i.Notes,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthBudgets = `-- name: MonthBudgets :many
SELECT c.id AS category_id, c.name, c.parent_id, COALESCE(b.amount_minor, 0)::bigint AS budget_minor
FROM fin_categories c
LEFT JOIN fin_budgets b ON b.category_id = c.id AND b.month = $1 AND b.space_id = c.space_id
WHERE c.space_id = $2 AND c.kind = 'expense'
ORDER BY c.parent_id NULLS FIRST, c.name
`

type MonthBudgetsParams struct {
	Month   time.Time
	SpaceID uuid.UUID
}

type MonthBudgetsRow struct {
	CategoryID  uuid.UUID
	Name        string
	ParentID    *uuid.UUID
	BudgetMinor int64
}

// Every expense category with the budget set for the month (base currency).
func (q *Queries) MonthBudgets(ctx context.Context, arg MonthBudgetsParams) ([]MonthBudgetsRow, error) {
	rows, err := q.db.Query(ctx, monthBudgets, arg.Month, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthBudgetsRow
	for rows.Next() {
		var i MonthBudgetsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.ParentID,
			&i.BudgetMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthExpenseByCategory = `-- name: MonthExpenseByCategory :many
SELECT t.category_id, a.currency, SUM(-t.amount_minor)::bigint AS spent_minor
FROM fin_transactions t
JOIN entities tx_e ON tx_e.id = t.id AND tx_e.deleted_at IS NULL
JOIN fin_accounts a ON a.id = t.account_id
WHERE t.space_id = $1 AND t.kind = 'expense' AND t.category_id IS NOT NULL
  AND t.occurred_on >= $2 AND t.occurred_on < $3
GROUP BY t.category_id, a.currency
`

type MonthExpenseByCategoryParams struct {
	SpaceID    uuid.UUID
	MonthStart time.Time
	MonthEnd   time.Time
}

type MonthExpenseByCategoryRow struct {
	CategoryID *uuid.UUID
	Currency   string
	SpentMinor int64
}

// What was spent in each category this month, per account currency. Go converts
// the amounts to the base currency, so mixed currencies never add up raw.
func (q *Queries) MonthExpenseByCategory(ctx context.Context, arg MonthExpenseByCategoryParams) ([]MonthExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, monthExpenseByCategory, arg.SpaceID, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthExpenseByCategoryRow
	for rows.Next() {
		var i MonthExpenseByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.Currency, &i.SpentMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthFlows = `-- name: MonthFlows :many
SELECT a.currency, t.kind, SUM(t.amount_minor)::bigint AS total_minor
FROM fin_transactions t
JOIN entities tx_e ON tx_e.id = t.id AND tx_e.deleted_at IS NULL
JOIN fin_accounts a ON a.id = t.account_id
WHERE t.space_id = $1 AND t.kind IN ('income', 'expense')
  AND t.occurred_on >= $2 AND t.occurred_on < $3
GROUP BY a.currency, t.kind
`

type MonthFlowsParams struct {
	SpaceID    uuid.UUID
	MonthStart time.Time
	MonthEnd   time.Time
}

type MonthFlowsRow struct {
	Currency   string
	Kind       string
	TotalMinor int64
}

// Income and expense for the month, per account currency. Transfers are not income.
func (q *Queries) MonthFlows(ctx context.Context, arg MonthFlowsParams) ([]MonthFlowsRow, error) {
	rows, err := q.db.Query(ctx, monthFlows, arg.SpaceID, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthFlowsRow
	for rows.Next() {
		var i MonthFlowsRow
		if err := rows.Scan(&i.Currency, &i.Kind, &i.TotalMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferLegs = `-- name: TransferLegs :many
SELECT id FROM fin_transactions WHERE transfer_id = $1 AND space_id = $2
`

type TransferLegsParams struct {
	TransferID *uuid.UUID
	SpaceID    uuid.UUID
}

func (q *Queries) TransferLegs(ctx context.Context, arg TransferLegsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, transferLegs, arg.TransferID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE fin_accounts
SET name = $1, kind = $2, opening_minor = $3, opened_on = $4
WHERE id = $5 AND space_id = $6
`

type UpdateAccountParams struct {
	Name         string
	Kind         string
	OpeningMinor int64
	OpenedOn     time.Time
	ID           uuid.UUID
	SpaceID      uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.Kind,
		arg.OpeningMinor,
		arg.OpenedOn,
		arg.ID,
		arg.SpaceID,
	)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE fin_settings
SET base_currency = $1, updated_at = $2, version = version + 1
WHERE space_id = $3 AND version = $4
RETURNING version
`

type UpdateSettingsParams struct {
	BaseCurrency    string
	Now             time.Time
	SpaceID         uuid.UUID
	ExpectedVersion int32
}

// Returns no rows when the expected version is stale, which the caller maps to 412.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.BaseCurrency,
		arg.Now,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE fin_transactions
SET amount_minor = $1, occurred_on = $2, category_id = $3,
    payee = $4, notes = $5
WHERE id = $6 AND space_id = $7
`

type UpdateTransactionParams struct {
	AmountMinor int64
	OccurredOn  time.Time
	CategoryID  *uuid.UUID
	Payee       *string
	Notes       *string
	ID          uuid.UUID
	SpaceID     uuid.UUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.AmountMinor,
		arg.OccurredOn,
		arg.CategoryID,
		arg.Payee,
		arg.Notes,
		arg.ID,
		arg.SpaceID,
	)
	return err
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO fin_budgets (id, space_id, category_id, month, amount_minor)
VALUES (uuidv7(), $1, $2, $3, $4)
ON CONFLICT (space_id, category_id, month) DO UPDATE SET amount_minor = EXCLUDED.amount_minor
`

type UpsertBudgetParams struct {
	SpaceID     uuid.UUID
	CategoryID  uuid.UUID
	Month       time.Time
	AmountMinor int64
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertBudget,
		arg.SpaceID,
		arg.CategoryID,
		arg.Month,
		arg.AmountMinor,
	)
	return err
}

const upsertRate = `-- name: UpsertRate :exec
INSERT INTO fin_rates (space_id, currency, rate_on, rate_e8)
VALUES ($1, $2, $3, $4)
ON CONFLICT (space_id, currency, rate_on) DO UPDATE SET rate_e8 = EXCLUDED.rate_e8
`

type UpsertRateParams struct {
	SpaceID  uuid.UUID
	Currency string
	RateOn   time.Time
	RateE8   int64
}

func (q *Queries) UpsertRate(ctx context.Context, arg UpsertRateParams) error {
	_, err := q.db.Exec(ctx, upsertRate,
		arg.SpaceID,
		arg.Currency,
		arg.RateOn,
		arg.RateE8,
	)
	return err
}
